### ISSUE TITLE
LAG - Lagrlond development

### ISSUE THREAD

**Issue by maxice8** [Post-Finem-Team/PostFinem_PreRelease#39]
# LAG - Lagrlond development

This is a list of content that is missing from Lagrlond, to help me keep track.

## Mission Tree:

- Conquest Branch
    - [x] Layout
    - [x] Scripting
    - [x] Review
    - [x] Localization
- Tall Branch
    - [x] Layout
    - [x] Scripting
    - [x] Review
    - [x] Localization
- Colonial Branch
    - [x] Layout
    - [x] Scripting
    - [x] Review
    - [x] Localization

## Government Reforms:

- [x] Lagr Republic (T1)
	- [x] Design
	- [x] Scripting
	- [x] Localization
	- [x] Auxiliary Events
- [x] Lowlander Naval Doctrine (T5)
	- [x] Design
	- [x] Scripting
	- [x] Localization
- [x] Empower the Provincial Things (T7)
	- [x] Design
	- [x] Scripting
	- [x] Localization
- [x] Dominance of the Merchant Princes (T2)
	- [x] Design
	- [x] Scripting
	- [x] Localization
- [x] Placcards of Tolerance (T4)
	- [x] Design
	- [x] Scripting
	- [x] Localization
- [x] Ceremonial Thinghalder (T6)
	- [x] Design
	- [x] Scripting
	- [x] Localization
- [x] Marginalism (T8)
	- [x] Design
	- [x] Scripting
	- [x] Localization

### General Flavour:

- [x] Martini Toren
	- [x] Design
	- [x] Scripting
	- [x] Localization

### Native Opposition Event Chain:

- [x] Iceni Revolt
	- [x] Scripting
  	- [x] Localization 
- [x] Ragni Revolt
  	- [x] Scripting
  	- [x] Localization
- [x] Cantiaci Revolt
  	- [x] Scripting
  	- [x] Localization
- [x] Trinovante Revolt
  	- [x] Scripting
  	- [x] Localization
- [x] Catuvellauni Revolt
	- [x] Scripting
	- [x] Localization

## Ideas

No changes are needed, they are very strong, and have been localised

**Comment by Chewyshoot** [comment]
Any way we can make this a template of sorts?

**Comment by maxice8** [comment]
Yes, but the template's content depends highly on the designed content.

If we want a template we can make it by super-category like (Missions, Events, Government Reforms) and have the issuer write it down.
