### ISSUE TITLE
Europeans see 4071 and Central Africans see 4701, no idea why

### ISSUE THREAD

**Issue by Chewyshoot** [Post-Finem-Team/PostFinem_PreRelease#43]
**Context**

- Europa Universalis IV version: 
- Post Finem version:
- Missing DLC:
- Other enabled mods:

**Describe the bug**
See title. Province history indicates it shouldn't happen, so I must just be missing something

**Instructions to reproduce the bug**
On startup

**Screenshots**

**Proposed fix**

**Additional context**
You're a handsom lad

**Comment by maxice8** [comment]
Closing as it was not filled correctly

**Comment by maxice8** [comment]
The following Technology groups are affected:

- Nomadic
- Western
- Anatolian
- Eastern
- Muslim

**Comment by maxice8** [comment]
See the message in the commit for explanation of the bug
