### ISSUE TITLE
Dom Tower not showing up

### ISSUE THREAD

**Issue by Chewyshoot** [Post-Finem-Team/PostFinem_PreRelease#72]
Artwork and buttons aren't there, not sure what's up.

**Comment by maxice8** [comment]
Investigating

**Comment by Chewyshoot** [comment]
buttons work ignore that part, it's just the art

**Comment by maxice8** [comment]
![image](https://github.com/Post-Finem-Team/PostFinem_PreRelease/assets/30738253/8d16e9d7-8e3e-42e4-9d0c-f33fc79bb29e)

Works fine on main

**Comment by Chewyshoot** [comment]
on main?

**Comment by maxice8** [comment]
on main

**Comment by Chewyshoot** [comment]
wasn't working for me on my branch or main

**Comment by Chewyshoot** [comment]
:thonk:

**Comment by maxice8** [comment]
lmao

**Comment by Chewyshoot** [comment]
get in chat pp head
